export const WARNA_UTAMA = '#55CB95';
export const WARNA_DISABLE = '#C8C8C8';
export const WARNA_SEKUNDER = "#E0F7EF";
export const WARNA_ABU_ABU = '#F4F4F4';
export const WARNA_WARNING =  '#FF4D00';
export const WARNA_BIRU = '#4982C1';
export const WARNA_PINK = '#FEE2E2';
export const WARNA_COKLAT ='#AEAA4E';
export const WARNA_MERAH = '#AE4E4E';
